kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-new
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/data"
